[[redirects]]
from = "https://www.christlutheranmhk.org/*"
to = "https://www.christlutheranmanhattan.org/:splat"
status = 301
force = true

[[redirects]]
from = "https://christlutheranmhk.org/*"
to = "https://www.christlutheranmanhattan.org/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.christlutheranmanhattan.com/*"
to = "https://www.christlutheranmanhattan.org/:splat"
status = 301
force = true

[[redirects]]
from = "https://christlutheranmanhattan.com/*"
to = "https://www.christlutheranmanhattan.org/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.christlutheranmhk.com/*"
to = "https://www.christlutheranmanhattan.org/:splat"
status = 301
force = true

[[redirects]]
from = "https://christlutheranmhk.com/*"
to = "https://www.christlutheranmanhattan.org/:splat"
status = 301
force = true

[[redirects]]
from = "/about.html"
to = "/about"
status = 301

[[redirects]]
from = "/mission.html"
to = "/about"
status = 301

[[redirects]]
from = "/what-we-believe.html"
to = "/beliefs"
status = 301

[[redirects]]
from = "/our-pastor.html"
to = "/our-pastor"
status = 301

[[redirects]]
from = "/photo-gallery.html"
to = "/"
status = 301

